### ISSUE TITLE
make val cheat

### ISSUE THREAD

**Issue by DrexWare** [conspiracylol/conspiracylol#1]
plz make val cheat
i will forcibly make my friend pay you. (he ain't gonna have a option but u do)
I will become ur discord kitten. (optional)
I will become ur #1 supporter and become media for vixen. (%100)

**Comment by DrexWare** [comment]
pwetty pwease

**Comment by DrexWare** [comment]
niggaer

make it or gay

**Comment by conspiracylol** [comment]
fuck valorant

**Comment by DrexWare** [comment]
> fuck valorant

but wh...whyyyy
